version: "3"

services:
  id-server:
    build: ./OAuth2.IdentityServer
    image: oauth2-identityserver
    ports:
      - 8080:80

  web-api:
    build: ./OAuth2.WebApi
    image: oauth2-webapi
    ports:
      - 8081:80

  client-app:
    build: ./OAuth2.ClientApp
    image: oauth2-clientapp
    depends_on:
      - id-server
      - web-api
    restart: on-failure
